# Generated by Django 4.1 on 2022-09-03 14:15

from django.db import migrations, models
import rent_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='year',
            field=models.IntegerField(default=1970),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(validators=[rent_app.models.year_validation]),
        ),
    ]
