# Generated by Django 4.1 on 2022-09-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0002_person_year_alter_movie_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.person')),
            ],
        ),
    ]
